# Generated by Django 5.0 on 2024-01-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBeers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('brewery', models.CharField(max_length=250, verbose_name='Производитель')),
                ('rating', models.IntegerField(verbose_name='Оценка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Пиво',
                'verbose_name_plural': 'Пива',
            },
        ),
    ]
